### ISSUE TITLE
Open an issue if you saw a bug in ZCombinator

### ISSUE THREAD

**Issue by Livinglist** [Livinglist/ZCombinator#2]

**Comment by irangareddy** [comment]
Hi @Livinglist, I'm Ranga Reddy. While browsing Hacker News, I stumbled upon some comments and discovered your app. I was thrilled to learn that it's open source. With my background in building iOS and Flutter apps, I've been eager to venture into multi-platform development for some time now. Instead of starting from scratch, I'd love to contribute to projects like this. After going through the app, I found we could improve the user experience. I'm determined to make it the number one client app for Hacker News.
